# Generated by Django 3.2.3 on 2021-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
