# Generated by Django 3.2.3 on 2021-10-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210704_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_eo',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='content_nl',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_nl',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_org',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_eo',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='title'),
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='title_nl',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_nl',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_org',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='title'),
        ),
    ]
