# Generated by Django 3.2.3 on 2021-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_eo', models.TextField(blank=True, default='', verbose_name='introduction')),
                ('introduction_nl', models.TextField(blank=True, default='', verbose_name='introduction')),
                ('introduction_org', models.TextField(blank=True, default='', verbose_name='introduction')),
                ('introduction_en', models.TextField(blank=True, default='', verbose_name='introduction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
