# Generated by Django 3.2.3 on 2021-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211107_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_eo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_nl',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_org',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='my_story_en',
            field=models.TextField(blank=True, default='', verbose_name='my_story'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='my_story_eo',
            field=models.TextField(blank=True, default='', verbose_name='my_story'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='my_story_nl',
            field=models.TextField(blank=True, default='', verbose_name='my_story'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='my_story_org',
            field=models.TextField(blank=True, default='', verbose_name='my_story'),
        ),
    ]
