# Generated by Django 3.2.3 on 2021-05-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='poems.poem')),
            ],
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanzas', to='poems.poem')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(default='', max_length=1024)),
                ('stanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='poems.stanza')),
            ],
        ),
    ]
