# Generated by Django 3.2.3 on 2021-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='line',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title',
        ),
        migrations.AddField(
            model_name='line',
            name='line_eo',
            field=models.CharField(default='', max_length=1024, verbose_name='line'),
        ),
        migrations.AddField(
            model_name='line',
            name='line_nl',
            field=models.CharField(default='', max_length=1024, verbose_name='line'),
        ),
        migrations.AddField(
            model_name='line',
            name='line_org',
            field=models.CharField(default='', max_length=1024, verbose_name='line'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_eo',
            field=models.CharField(default='', max_length=254, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_nl',
            field=models.CharField(default='', max_length=254, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='title',
            name='title_org',
            field=models.CharField(default='', max_length=254, verbose_name='title'),
        ),
    ]
