# Generated by Django 3.2.3 on 2021-05-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20210523_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='line_org',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title_org',
        ),
    ]
