# Generated by Django 3.2.3 on 2021-06-12 12:49

from django.db import migrations

def back_fill_author(apps, schema_editor):
    Poem = apps.get_model('poems', 'Poem')
    Author = apps.get_model('poems', 'Author')

    for poem in Poem.objects.filter(author_link=None):
        author = Author.objects.filter(name=poem.author).first()
        if author is None:
            author = Author.objects.create(name=poem.author)
        poem.author_link = author
        poem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_auto_20210612_1248'),
    ]

    operations = [
        migrations.RunPython(
            back_fill_author,
            reverse_code=migrations.RunPython.noop,
        )
    ]
