# Generated by Django 3.2.3 on 2021-06-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_remove_poem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poems.author'),
        ),
    ]
