# Generated by Django 3.2.3 on 2021-06-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_alter_poem_author_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='author_link',
            new_name='author',
        ),
    ]
