# Generated by Django 3.2.3 on 2021-06-12 19:11

from django.db import migrations, models

def back_fill_author_name(apps, schema_editor):
    Author = apps.get_model('poems', 'Author')

    for author in Author.objects.all():
        author.name_eo = author.name
        author.name_nl = author.name
        author.name_org = author.name
        author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_rename_author_link_poem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_eo',
            field=models.CharField(default='', max_length=254, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_nl',
            field=models.CharField(default='', max_length=254, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_org',
            field=models.CharField(default='', max_length=254, verbose_name='name'),
        ),
        migrations.RunPython(
            back_fill_author_name,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
