# Generated by Django 3.2.3 on 2021-06-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_auto_20210612_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eo', models.CharField(default='', max_length=254, verbose_name='name')),
                ('name_nl', models.CharField(default='', max_length=254, verbose_name='name')),
                ('name_org', models.CharField(default='', max_length=254, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='country_of_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_of_birth', to='poems.country'),
        ),
    ]
