# Generated by Django 3.2.3 on 2021-06-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0014_auto_20210612_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='abstract_eo',
            field=models.TextField(default='', verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='poem',
            name='abstract_nl',
            field=models.TextField(default='', verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='poem',
            name='abstract_org',
            field=models.TextField(default='', verbose_name='abstract'),
        ),
    ]
