# Generated by Django 3.2.3 on 2021-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0015_auto_20210612_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
