# Generated by Django 3.2.3 on 2021-06-26 07:32

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('poems', '0016_poem_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
