# Generated by Django 3.2.3 on 2021-07-04 18:39

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('poems', '0018_author_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='portrait',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portrait', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
