# Generated by Django 3.2.3 on 2021-07-06 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0019_auto_20210704_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
