# Generated by Django 3.2.3 on 2021-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0023_auto_20210715_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='abstract_en',
            field=models.TextField(blank=True, default='', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='abstract_eo',
            field=models.TextField(blank=True, default='', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='abstract_nl',
            field=models.TextField(blank=True, default='', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='abstract_org',
            field=models.TextField(blank=True, default='', verbose_name='abstract'),
        ),
    ]
