# Generated by Django 3.2.3 on 2021-10-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0024_auto_20210912_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='stanza',
            options={'ordering': ['pk']},
        ),
    ]
