# Generated by Django 3.2.3 on 2021-09-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0002_partofspeach_part_of_speach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partofspeach',
            old_name='part_of_speach',
            new_name='acronyms',
        ),
    ]
