# Generated by Django 3.2.3 on 2021-10-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0004_remove_partofspeach_acronyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_eo', models.CharField(blank=True, default='', max_length=254, verbose_name='noun')),
                ('noun_nl', models.CharField(blank=True, default='', max_length=254, verbose_name='noun')),
                ('noun_org', models.CharField(blank=True, default='', max_length=254, verbose_name='noun')),
                ('noun_en', models.CharField(blank=True, default='', max_length=254, verbose_name='noun')),
                ('misc_eo', models.CharField(blank=True, default='', max_length=254, verbose_name='misc')),
                ('misc_nl', models.CharField(blank=True, default='', max_length=254, verbose_name='misc')),
                ('misc_org', models.CharField(blank=True, default='', max_length=254, verbose_name='misc')),
                ('misc_en', models.CharField(blank=True, default='', max_length=254, verbose_name='misc')),
                ('verb_eo', models.CharField(blank=True, default='', max_length=254, verbose_name='verb')),
                ('verb_nl', models.CharField(blank=True, default='', max_length=254, verbose_name='verb')),
                ('verb_org', models.CharField(blank=True, default='', max_length=254, verbose_name='verb')),
                ('verb_en', models.CharField(blank=True, default='', max_length=254, verbose_name='verb')),
                ('acronym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_groups', to='wordlist.acronym')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='word',
            name='part_of_speach',
        ),
        migrations.DeleteModel(
            name='PartOfSpeach',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
